PACKAGE_NAME="f81601a"
PACKAGE_VERSION="1.03.20250515"
BUILT_MODULE_NAME[0]="f81601a"
DEST_MODULE_LOCATION[0]="/kernel/drivers/net/can"
AUTOINSTALL="yes"
MAKE[0]="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build modules"
CLEAN="make -C ${kernel_source_dir} M=${dkms_tree}/${PACKAGE_NAME}/${PACKAGE_VERSION}/build clean"
